name: flutter_eg_logger_easier
description: "Demonstrates how to use the logger_easier plugin."

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  logger_easier: 1.0.0
    # path: ../

  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

