name: logger_easier
description: A modern logging management solution tailored specifically for Dart and Flutter applications. It provides a highly flexible and feature-rich logging system designed to simplify developers' log management while offering significant customization capabilities.
homepage: https://github.com/jacklee1995/flutter_logger_easier
repository: https://github.com/jacklee1995/flutter_logger_easier

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  path: ^1.9.0
  intl: ^0.20.1
  archive: ^4.0.2
  vm_service: ^14.2.5
  stack_trace: ^1.11.1
  synchronized: ^3.3.0+3
  crypto: ^3.0.3
  encrypt: ^5.0.3

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.14
  typed_data: ^1.4.0

screenshots:
  - description: "Logger easier logo."
    path: logo.png