name: logger_easier_example
description: "Demonstrates how to use the logger_easier plugin."

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  logger_easier:
    # When depending on this package from a real application you should use:
    #   logger_easier: ^x.y.z
    path: ../
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

