name: logger_easier
description: A modern logging management solution tailored specifically for Dart and Flutter applications. It provides a highly flexible and feature-rich logging system designed to simplify developers' log management while offering significant customization capabilities.
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.0
  intl: ^0.20.1
  archive: ^4.0.2
  vm_service: ^14.2.5
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.14
  typed_data: ^1.4.0
screenshots:
  - description: "Example Picture."
    path: ./example.png
