name: json_middleware_for_logger_easier
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  path: ^1.9.0
  json_annotation: ^4.9.0
  logger_easier: 1.0.0
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0