name: eg_logger_easier
description: "A sample example to demonstrates how to use the logger_easier."
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  logger_easier: 
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
